apiVersion: v1
kind: Service
metadata:
  name: rails-rayces
  namespace: raycesv3
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: rails-api
  type: LoadBalancer
