apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-rayces
  namespace: raycesv3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-api
  template:
    metadata:
      labels:
        app: rails-api
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c']
        args:
          - |
            echo "Waiting for postgres-rayces:5432..."
            until nc -z ${POSTGRES_HOST} ${POSTGRES_PORT}; do
              echo "Postgres is unavailable - sleeping"
              sleep 2
            done
            echo "Postgres is up - continuing"
        envFrom:
          - secretRef:
              name: raycesv3-environment

      containers:
      - name: rails-api
        image: rayces-backend
        ports:
        - containerPort: 4000

        envFrom:
          - secretRef:
              name: raycesv3-environment

        command: [ "sh", "-c" ]
        args:
          - |
            echo "Starting Rails app..." && \
            rm -f tmp/pids/server.pid && \
            bundle exec rails db:create db:migrate && \
            bundle exec rails s -b '0.0.0.0' -p ${RAILS_PORT:-4000} -e ${RAILS_ENV:-development}

        # Optional healthchecks
        # readinessProbe:
        #   httpGet:
        #     path: /up
        #     port: 4000
        # livenessProbe:
        #   httpGet:
        #     path: /up
        #     port: 4000
