apiVersion: v1
kind: Service
metadata:
  name: nextjs-rayces
  namespace: raycesv3
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nextjs-rayces
  type: LoadBalancer
