# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources will be deployed into this namespace.
# Kustomize will add the namespace to any resource that doesn't have one.
namespace: raycesv3

secretGenerator:
  - name: raycesv3-environment # Name of the Kubernetes Secret object
    type: Opaque
    envs:
      - .env # Reads this gitignored file

resources:
  # List of all Kubernetes manifests to be applied.
  - namespace.yaml
  - storage.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  #- rails-seeding-job-run-only-once.yaml
