apiVersion: v1
kind: Service
metadata:
  name: postgres-rayces
  namespace: raycesv3
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: LoadBalancer
